version: '3.8'

services:
  zapoli:
    container_name: 210maxi
    image: dezhtech/210maxi:latest
    restart: unless-stopped
    ports:
      - "2100:2100"
    environment:
      RELAY_NAME: "210Maxi"
      RELAY_PUBKEY: "your_pubkey"
      RELAY_DESCRIPTION: "A Nostr relay"
      RELAY_URL: "wss://example.com"
      RELAY_ICON: "https://example.com/icon.png"
      RELAY_BANNER: "https://example.com/banner.png"
      RELAY_CONTACT: "https://example.com"
      WORKING_DIR: "210maxi_wd/"
      RELAY_PORT: ":2100"
    volumes:
      - 210maxi_data:/app/210maxi_wd/
    networks:
      - 210maxi_network

volumes:
  210maxi_network:
