version: '3.8'

services:
  bunklay:
    container_name: nwclay
    image: dezhtech/nwclay:latest
    restart: unless-stopped
    ports:
      - "3334:3334"
    environment:
      RELAY_NAME: "nwclay"
      RELAY_PUBKEY: "your_pubkey"
      RELAY_DESCRIPTION: "A Nostr relay"
      RELAY_URL: "wss://abc.com"
      RELAY_ICON: "https://your-icon-url.png"
      RELAY_BANNER: "https://your-banner-url.png"
      RELAY_CONTACT: "https://dezh.tech"
      RELAY_PORT: ":3334"
      WORKING_DIR: "nwclay_wd/"
      KEEP_IN_MINUTES: 10
      ACCEPT_WINDOW_IN_MINUTES: 1
    volumes:
      - nwclay_data:/app/nwclay_wd/
    networks:
      - nwclay_network

volumes:
  nwclay_network:
