version: '3.8'

services:
  bunklay:
    container_name: nwclay
    image: dezhtech/nwclay:latest
    restart: unless-stopped
    ports:
      - "3334:3334"
    environment:
      RELAY_NAME: "NWClay"
      RELAY_PUBKEY: "your_pubkey"
      RELAY_DESCRIPTION: "A Nostr relay for nwc apps."
      RELAY_URL: "wss://example.com"
      RELAY_ICON: "https://example.com/icon.png"
      RELAY_BANNER: "https://example.com/banner.png"
      RELAY_CONTACT: "https://example.com"
      RELAY_PORT: ":3334"
      WORKING_DIR: "nwclay_wd/"
      KEEP_IN_MINUTES: 10
      ACCEPT_WINDOW_IN_MINUTES: 1
    volumes:
      - nwclay_data:/app/nwclay_wd/
    networks:
      - nwclay_network

volumes:
  nwclay_data:
