version: '3.8'

services:
  bunklay:
    container_name: bunklay
    image: dezhtech/bunklay:latest
    restart: unless-stopped
    ports:
      - "3334:3334"
    environment:
      RELAY_NAME: "Bunklay"
      RELAY_PUBKEY: "your_pubkey"
      RELAY_DESCRIPTION: "A Nostr relay"
      RELAY_URL: "wss://example.com"
      RELAY_ICON: "https://example.com/icon.png"
      RELAY_BANNER: "https://example.com/banner.png"
      RELAY_CONTACT: "https://example.com"
      RELAY_PORT: ":3334"
      WORKING_DIR: "bunklay_wd/"
      KEEP_IN_MINUTES: 10
      ACCEPT_WINDOW_IN_MINUTES: 1
    volumes:
      - bunklay_data:/app/bunklay_wd/
    networks:
      - bunklay_network

volumes:
  bunklay_data:
