version: '3.8'

services:
  zapoli:
    container_name: pages
    image: dezhtech/pages:latest
    restart: unless-stopped
    ports:
      - "3334:3334"
    environment:
      RELAY_NAME: "Pages"
      RELAY_PUBKEY: "your_pubkey"
      RELAY_DESCRIPTION: "A Nostr relay"
      RELAY_URL: "wss://example.com"
      RELAY_ICON: "https://example.com/icon.png"
      RELAY_BANNER: "https://example.com/banner.png"
      RELAY_CONTACT: "https://example.com"
      WORKING_DIR: "pages_wd/"
      RELAY_PORT: ":3334"
      ADMIN_PUBKEYS: ""
      MODERATOR_PUBKEYS: ""
      DISC_RELAYS: "nos.lol,purplepag.es,relay.nostr.lol,jellyfish.land,relay.primal.net,nostr.mom,nostr.wine,nostr.land"
    volumes:
      - pages_data:/app/pages_wd/
    networks:
      - pages_network

volumes:
  pages_data:
