version: '3.8'

services:
  zapoli:
    container_name: chapar
    image: dezhtech/chapar:latest
    restart: unless-stopped
    ports:
      - "1717:1717"
    environment:
      RELAY_NAME: "Chapar"
      RELAY_PUBKEY: "your_pubkey"
      RELAY_DESCRIPTION: "We only accept kin 1059 events!"
      RELAY_URL: "wss://example.com"
      RELAY_ICON: "https://example.com/icon.png"
      RELAY_BANNER: "https://example.com/banner.png"
      RELAY_CONTACT: "https://example.com"
      WORKING_DIR: "chapar_wd/"
      RELAY_PORT: ":1717"
    volumes:
      - chapar_data:/app/chapar_wd/
    networks:
      - chapar_network

volumes:
  chapar_network:
