name: Create and publish Docker image for 210maxi relay

on:
  push:
    tags:
      - '210maxi@v*'

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/210maxi
  BASE_TAG: latest

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Build and push Docker images
        id: push
        uses: docker/build-push-action@v5
        with:
          context: 210maxi
          dockerfile: dockerfile
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ env.IMAGE_NAME }}:${{ env.BASE_TAG }}
          labels: ${{ steps.meta.outputs.labels }}
